name: quick_cart
description: "QuickMart - A modern ecommerce Flutter app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.9.0
  internet_connection_checker: ^3.0.1
  cached_network_image: ^3.4.1

  package_info_plus: ^8.3.1

  # Local storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.2
  smooth_page_indicator: ^1.2.1

  # Navigation
  go_router: ^16.2.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Dependency injection
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Generate localization
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic